// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  // Used by the Prisma CLI (migrate/introspect) — Supabase's pooled/PgBouncer
  // connection doesn't support the DDL + prepared statements migrations need,
  // so this must be the direct (non-pooled) connection string.
  // The app's runtime client uses DATABASE_URL (pooled) via the adapter in lib/prisma.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
